<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * manageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class manageRepository extends EntityRepository
{
}
